version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - SLACK_VERIFICATION_TOKEN
    ports:
      - "3000:3000"
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
